### ISSUE TITLE
保存先指定ウインドウが無限に開かれる不具合

### ISSUE THREAD

**Issue by tana3n** [tana3n/fanbox-downloader#1]
AUOのレビュー（[reviews/1979659](https://addons.mozilla.org/ja/firefox/addon/fanbox-downloader/reviews/1979659/)）
曰く  
Firefoxの設定(about:preference)にある```ファイルごとに保存先を指定する```にチェックしていると、
DLする数だけ無限に出てくるっぽい。
- 確認環境  
fanbox-downloader 1.3.9  
Firefox 116.0b3

**Comment by tana3n** [comment]
WebExtensionのAPIのdownloads.downloadの挙動を確認した感じでは、  
[downloads.download() - Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download)
saveAsが未定義だとFirefoxの設定に依存。
- true
  強制で名前を付けて保存ダイアログを表示
- false
  強制で指定した名前で表示せずにdownloadを実行する模様。  

とりあえず副作用はなさそうなので、一旦これで対応する。  

これはあくまでダイアログ表示させている時に無限に出てくる挙動その物を封じ込んでいるだけで、表示されたときのハンドリングとしては不適切。  
厳密にbackgroud側Scriptでダウンロードの処理を行う際にダウンロード完了なりキャンセルなりのメッセージをcontent_scriptsにレスポンスを返すまでを行う必要があって手間取りそうなので、一旦これにてfixとする。

**Comment by ryuuutyenn** [comment]
こちらのアドオンをいつも使用させていただいています。ありがとうございます。

こちらの修正をされてからだと思いますが、
>  強制で指定した名前で表示せずにdownloadを実行する模様。

すでに同じ名前のファイルが有る場合は(1)が付与されて強制的に保存されてしまいます。
気づかぬ内に(1)が大量に生成されてしまい、少し不便です。
大変お手数ですが、同じファイルがある等の場合は確認のダイアログが出るように検討いただけないでしょうか？

**Comment by tana3n** [comment]
レポートありがとうございます。
えーと、実はこちらの想定通りの挙動でして、1.3.9以前でも元々名前を付けて保存ダイアログを表示してない環境ではその挙動であることは確認していました。
確かにいけてないなと思っています。が、対処コストが高いので、なんとか重複させずに運用する方向に持っていきたいなと言うのが私個人の意見になりますが、その前に対処コストが高い理由を書いておきます。

### 重複対処時の問題点
#### ファイルの重複チェックがdownloads.downloadのconflictActionでしか行えない

この拡張に限らずWebExtensionのAPI的に直接ローカルのダウンロードフォルダの読み書きが一切行えない仕様です。ダウンロード自体もダウンロードフォルダへ直接描き込んでいるのではなくブラウザ側（のAPI）にファイル名、URLなどのオプションを渡して代行して貰う形になります。セキュリティ上仕方ないものの制約条件として非常に大きく、重複チェックは実際にダウンロードAPIを叩いた時の挙動を見ることでしか判定出来ない形になります。
その上downloads.download APIのオプションであるconflictActionは、上書きorプロンプトor(1)みたいに名前を変えて保存のいずれかしか行えませんのでチェックに使うには微妙そうな感じです。

仮に重複時にプロンプトを出す場合(```pronpt```)は、以下の副作用が要されます。
- 現状では保存先指定ウインドウが無限に開かれる挙動が再発
- プロンプトが出てキャンセルしたときのハンドリングを行う必要あり
- 複数枚DLしているときは最悪の場合100枚近く手動で名前を付けて保存をする必要がある（結局削除or移動するしかない）
これらは  
> これはあくまでダイアログ表示させている時に無限に出てくる挙動その物を封じ込んでいるだけで、表示されたときのハンドリングとしては不適切。

と書いてあるとおり、ダイアログその物を表示させない事により回避しているからです。また、3つ目のは、最終的に使用者がファイル操作を行わないと解消することが出来ないのが問題になるかなと思います（手動削除するのとさほど変わらない）
根本的対処をするには、  該当のページを開いているタブ側のスクリプトとダウンロード実行用のbackgroud側スクリプトのメッセージのやりとりを適切に行う必要があり（現状ではタブ側のスクリプトからbackgroud側スクリプトにDownloadリクエスト送るだけでACK処理をしていない状態）、ACKを返す場合の処理が結構問題でACKの受けを同期で待つ必要（そこで何らかの理由で何もレスポンスがなかった場合にデッドロックしてしまう可能性があるので避けたい形です。（キャンセルを押してください状態にするのも良くないという認識です）

他の二つの選択肢も一応あげておくと```overwrite```は強制で上書きするのもよくないし、最後の```uniquify```は現状ですね。
### Workaroundの提案
そこでですが、投稿ページの中身が同一ではある保証がないことが増えてきているみたいですし、保存時のフォルダに保存日時を入れてデフォルト値に含ませることで可能な限り重複させない運用に持っていくのが無難かなと思っているのですがいかがでしょうか？今ぱっと思いついたのがこのぐらいだったので、もうちょっと良い方法があるかもしれませんが、ToDo的に実装するつもりでしたので、やっておこうかなと思います。
