### ISSUE TITLE
重複時に(1)や(2)がファイル名の末尾についてダウンロードされる

### ISSUE THREAD

**Issue by tana3n** [tana3n/fanbox-downloader#2]
#1 で触れられた件について。

**Comment by ryuuutyenn** [comment]
(スレッド分けられたようですので、こちらでコメントさせていただきます。)
ご返事ありがとうございます。
わかりやすく説明いただきありがとうございました。

> 保存時のフォルダに保存日時を入れてデフォルト値に含ませることで可能な限り重複させない運用

の対策は素晴らしいと思います。
しかし、私がご提案した目的としては、重複したことがわかって、同じコンテンツを重複して保存しないになります。
簡単には実現できなさそうですの、ひとまずは運用でカバーしようと思います。
(DLフォルダをみて（1）ついたらまとめて削除する)

検討いただきありがとうございます。
このアドオンがあるだけで大変助かっていますので、ご負担にならない範囲で聞き流していただければと思います。

**Comment by tana3n** [comment]
申し訳ないです。そう言ってもらえるとかなり助かります。
Issueは件のMacroを実装次第閉じておきますー。

**Comment by tana3n** [comment]
ダウンロード履歴を持っておけば履歴を持っている物に対しては対応可能では？と他で突っ込みが入ったのでメモ  

履歴保持の実装に関して何も考えていなかったので今後要調査。
一旦別のIssuesに切り直して気が向いたら対応する。
