### ISSUE TITLE
保存に失敗するファイル名

### ISSUE THREAD

**Issue by iantr182023** [tana3n/fanbox-downloader#4]
便利なアドオンを公開していただきありがとうございます。
表題の通り保存に失敗するケースに遭遇したため報告をいたしました。
- 確認環境
fanbox-downloader 1.3.11
Firefox 116.0.3 (64 ビット)

失敗するケース
1. `$Title$`に"|"(バーティカルバー)が含まれる投稿の保存
2. `$fanboxname$`の先頭に半角スペースが入っていて、フォルダやファイル名の先頭に`$fanboxname$`を設定している時の保存

2は結構不思議で、fanboxのアイコン横にある投稿者名には半角スペースが入っていないようにみえるのですが、
`$fanboxname$`には半角スペースが入って返ってきているようでした。

可能でしたら1は"_"などの無害な仕切り文字に、
2は半角スペースを削除するような整形を入れていただけると嬉しいです。

対応コストが問題となるようでしたら、正直かなりのレアケースと思いますので捨て置いていただいて結構です。

どちらも１件しか遭遇しておらずここで名指しするように書くのは憚られるため、
例示が必要でしたら適当なクローズなメッセージなどでお送りできればと思います。

**Comment by tana3n** [comment]
詳細なバグレポート、ありがとうございます。
具体的な内容で調査を行いやすかったです。感謝します。  
ここに具体例が載ってしまうと中々よろしくないなとは思っていましたので、配慮も非常に助かりました。  

では、2件のケースについてのお答えしますと、  

1件目は、単純にファイル名に指定できない、所謂Windows環境での禁則文字を踏んでいるようでした。
今までは真面目に対応していなかったので対応するようにしました。（やっとけという話ではあります）
ちょっと考えたのですが、今回は以下の組み合わせで変換するようにしました。
https://github.com/tana3n/fanbox-downloader/blob/7107523905c1e8dc745708fa907280619a4318cd/fanbox-downloader.js#L186-L187

任意の文字に置換したいとか、そういう文字はdropさせた方がいいとか諸々分かれそうなら、設定で対応してもよさそうですね。要望次第かなあ……
別件のDL時の挙動といい、現状の設定項目では痒いところに手が届かない感はあるので、他のタスクが空いたときの実装項目として頭に入れておきます。

2件目は、投稿者名欄の表示上は、頭に半角スペースが入っていると削られて表示されるようです。  
開発者モードで投稿者名のところを要素として選択し、適当に文字を書き換えてみたところ、  
頭に半角スペースが入っていても反映されていないことが確認できました。  
おそらく投稿者名の頭に半角スペースが入ってしまってるのではないのかなとは思います。
ただ、これに限らず設定の書き方で起こりうる状態でしたので、リネームの最後らへんで対応入れました。これで問題は起こらなくなったと思います。

既にamoにはpush済みですので、近いうちに更新が行えるようになると思います。手動でも設定から更新が行えると思います。

諸々書くこととしても修正としても多分大丈夫だとは思うのですが、もし直ってなかったりおかしなこといってたら連絡ください。よろしくお願いいたします。（issueは修正が確認できるまで開けておきます）

**Comment by iantr182023** [comment]
返信、ご対応ありがとうございます。

1件目について、文字が変換されて保存が正しく完了することを確認いたしました。

2件目ですが、こちらは保存がされないままであることを確認いたしました。
修正を拝見したところファイル名の先頭一致で空白を消去されていることと思うのですが、
デフォルト設定のように`fanbox-downloader/$fanboxname$...`などフォルダ区切りの後ろに置かれた
頭に空白を含む`$fanboxname$`はリネームがされないように思います。
なので、私の最初の質問は若干の訂正が必要で、
誤：フォルダやファイル名の先頭に`$fanboxname$`を設定している時
正：フォルダ区切りの後ろに`$fanboxname$`を設定している時
に失敗していたという感じでしょうか。

考えられる対策としては`/`の後ろに空白が続くパターンを`/`単独に置き換えるなどは如何でしょうか。

**Comment by tana3n** [comment]
あーーー単純に私の考慮漏れですね......  
直しておきました。pushはしといたのでそのうち反映されると思います……

**Comment by iantr182023** [comment]
先ほど最新版に更新し、両件ともに保存ができるようになっていることを確認いたしました。

迅速なご対応ありがとうございました。

**Comment by tana3n** [comment]
いえいえ、大丈夫そうで良かったです。
