### ISSUE TITLE
1.3.14でダウンロードが始まらない

### ISSUE THREAD

**Issue by ryuuutyenn** [tana3n/fanbox-downloader#6]
いつもありがとうございます。
自分のPC環境だけかもしれませんが、1.3.14で動作していないようです。
Win11
Firefox 117.0.1 
他に必要な情報あれば提供いたします。

**Comment by tana3n** [comment]
えーっと、数日前に1.3.13で動かないっぽいのを対応したんですが、どうやらその追従する意味が無くなってしまい（プラットフォーム側の処理が戻ったっぽい？）ホント数分前にrevertしたものをamoに投げ込んできて承認通知までは確認したので、一旦それ試して貰えますか？（手動更新でいけると思います）

**Comment by ryuuutyenn** [comment]
1.3.15で無事動作しました！

**Comment by tana3n** [comment]
issues/7をみてる感じこれと関係がありそうだったのでメモ
