### ISSUE TITLE
ダウンロードが実行されない

### ISSUE THREAD

**Issue by iantr182023** [tana3n/fanbox-downloader#7]
いつも便利に使わせていただいております、ありがとうございます。

先週までは保存が行われていたのですが、昨日今日あたりから保存が実行されなくなってしまい、ご報告をいたしました。
- 確認環境(2024-01-20)
fanbox-downloader 1.3.15
Firefox 116.0.3 (64 ビット)

- 症状
保存ボタンを押してもダウンロードが開始されない

fanbox側の書式変更あたりではないかと思うのですが、
getDate中でnullが返ってきて失敗しているように見えます。

**Comment by tana3n** [comment]
あーーーーーgetDateで大体把握出来ました。ありがとうございます。
過去のIssue(https://github.com/tana3n/fanbox-downloader/issues/6 )でも関わっていた件で、
たまに挙動がおかしいことは把握してたので一旦Workaroundで失敗しても続投するようにしておきます。
いやーこれどうしましょ……？

**Comment by tana3n** [comment]
対応入れてAMOに投げてきたので、多分動く気がします。最悪コケても1970/01/01になるけれど、一応落とせるようにはなっているはずです。

**Comment by iantr182023** [comment]
1.3.16に更新をしたところ保存が成功し、日時も取得できていることを確認いたしました。

ご対応ありがとうございました。

**Comment by tana3n** [comment]
問題なさそうなのと閉じるのを忘れていたので閉じます
